
const char WIFI_SSID[] =          "YOUR_WIFI_SSID_HERE";
const char WIFI_PASSWORD[] =      "YOUR_WIFI_PASSWORD_HERE";

const char AWS_IOT_ENDPOINT[] =   "YOUR_AWS_IOT_ENDPOINT_HERE";
const char AWS_IOT_THING_NAME[] = "YOUR_CAMERA_NAME_HERE";
